version: "3.4"
services:
  master:
    hostname: master
    image: jkhlr/pytorch-mpi
    cap_add:
      - SYS_PTRACE
    ports:
      - 127.0.0.1:22:22
    networks:
      - net
    volumes:
      - ./src:/home/pi/src
  slave:
    hostname: slave
    image: jkhlr/pytorch-mpi
    cap_add:
      - SYS_PTRACE
    networks:
      - net
    volumes:
      - ./src:/home/pi/src

networks:
  net:
    driver: bridge