version: "3.4"
services:
  master:
    hostname: master
    image: jkhlr/pytorch-mpi
    ports:
      - 127.0.0.1:22:22
    networks:
      - net
    volumes:
      - ./src:/home/pi/src
      - ./hostfile:/home/pi/hostfile
    cap_add:
      - SYS_PTRACE
  slave:
    hostname: slave
    image: jkhlr/pytorch-mpi
    networks:
      - net
    volumes:
      - ./src:/home/pi/src
    cap_add:
      - SYS_PTRACE

networks:
  net:
    driver: bridge